### ISSUE TITLE
Can't import the library

### ISSUE THREAD

**Issue by liepaja** [sam0x17/crystal-mongo-orm#1]
`while requiring "mongo-orm": can't find file'mongo-orm'` is thrown.
Also tried importing just the "mongo" library, then: `undefined constant Mongo::ORM::Document`

How do you import this?

**Comment by feliksg** [comment]
@liepaja Currently, you can use `require "mongo-orm/src/mongo_orm"`.

**Comment by d4ins** [comment]
@feliksg Hi, can you update readme with this require information?
