### ISSUE TITLE
Not working with crystal 0.26.1 - JSON::Type

### ISSUE THREAD

**Issue by mniak** [sam0x17/crystal-mongo-orm#10]
```
Error target TesteCrystal failed to compile:
Error in src/TesteCrystal.cr:1: while requiring "mongo_orm"

require "mongo_orm"
^

in lib/mongo_orm/src/mongo_orm.cr:2: while requiring "./mongo_orm/*"

require "./mongo_orm/*"
^

in lib/mongo_orm/src/mongo_orm/document.cr:2: while requiring "./fields"

require "./fields"
^

in lib/mongo_orm/src/mongo_orm/fields.cr:4: undefined constant JSON::Type

  alias Type = JSON::Type | DB::Any
               ^~~~~~~~~~

```

**Comment by sam0x17** [comment]
yes I am aware, unfortunately even if I fix this the upstream mongo.cr package is still broken on newer versions of crystal, so we are stuck until that gets fixed

**Comment by mniak** [comment]
In my pull request #11 I reference the branch 0.25.1 from mongo.cr that is not broken.
My tests (crystal spec) are completing successfully.

**Comment by mniak** [comment]
I also fixed this error in the pull request mentioned above.

**Comment by sam0x17** [comment]
@mniak I apologize this is excellent and seems to fix all issues -- merging!!!

**Comment by mniak** [comment]
@sam0x17 Thanks for the opportunity to collaborate!
