### ISSUE TITLE
Can't convert to JSON

### ISSUE THREAD

**Issue by aigarsdz** [sam0x17/crystal-mongo-orm#13]
After calling `#to_json` on a query result, i get an error:

`no overload matches 'BSON::ObjectId#to_json' with type JSON::Builder`

Am I doing something wrong or is this functionality not supported? 

Disclaimer: I'm new to Crystal and Amber.

**Comment by sam0x17** [comment]
Thanks for catching this. That part of the code was untested and carried over from a very old version of granite orm. Now you should be able to call `.to_json` on any mongo_orm object. That said, do know that Mongo uses something called BSON, which is slightly different, and calling `.to_bson` will already give you a BSON object, and `.to_bson.to_s` is very similar to JSON. The `.to_json` method I wrote will give you crystal-formatted datetime values, while the `.to_bson` method will give you things in Mongo's internal formats.

**Comment by aigarsdz** [comment]
That's good to know, thank you!
