### ISSUE TITLE
No support for array types?

### ISSUE THREAD

**Issue by SteffanPerry** [sam0x17/crystal-mongo-orm#8]
Unless I am missing something, Arrays are not currently supported?

**Comment by sam0x17** [comment]
I could be wrong, but `embeds_many` might be what you're looking for. If you think that doesn't cover what you're looking for I'd be happy to accept a pull request adding this as a feature -- I'm much more familiar with PostgreSQL than mongo so this was sort of an adventure into uncharted territory for me.

Reference: https://github.com/sam0x17/mongo_orm#embedded-documents

**Comment by SteffanPerry** [comment]
The embedded document is technically an array of document, example

```
{id: 1, title: 'My Post', comments: [{id: 1, comment: 'hello'}, {id: 2, comment: 'Hi'}]}
```

mongo allows standard arrays which can be searched and (maybe more importantly) indexed on:

Something that would allow the following would make this super powerful:


```
class BlogPost < Mongo::ORM::EmbeddedDocument
  field title : String
  field tags : Array # (no class or model for tags needed)
  field user_ids : Array
  embeds_many :comments
end

=> {id: 1, title: 'My Post', comments: [{id: 1, comment: 'hello'}, {id: 2, comment: 'Hi'}], tags: ['blog', 'post']. user_ids: [1,2,3]}
```

I am new to  Crystal and the C world in general, ill see if I can get something to work.

**Comment by sam0x17** [comment]
Ok cool -- let me know if you need any help navigating the code. This is largely just based on GraniteORM modded to hook up to Mongo instead of SQL with a few features that I added.

**Comment by sam0x17** [comment]
On that note if you can think of a good way of including index management in this shard I'd be interested. I never got as far as indexes.
