### ISSUE TITLE
Not able to install mongo_orm

### ISSUE THREAD

**Issue by aarthikrao** [sam0x17/crystal-mongo-orm#9]
Failed git branch --list --column=never --contains 86c9e530c0ac980ed7b15e653746bc5b6f2527fc (no such commit 86c9e530c0ac980ed7b15e653746bc5b6f2527fc). Maybe a commit, branch or file doesn't exist?

**Comment by aarthikrao** [comment]
We have to add the mongo_orm dependency after mongo

**Comment by sam0x17** [comment]
Let me know if you need me to make any changes -- I gather you were able to resolve your issue?
